language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install . --quiet --use-mirrors
  - pip install nose simplejson Flask-SQLAlchemy Flask-MongoEngine Flask-Peewee Flask-Mail mock --quiet --use-mirrors
  - pip install oauth2client google-api-python-client foursquare --quiet --use-mirrors
  - pip install https://github.com/bear/python-twitter/archive/v3.0.zip
  - pip install http://github.com/pythonforfacebook/facebook-sdk/tarball/master --quiet

before_script:
  - mysql -e 'create database flask_social_test;'

services:
  - mongodb

script: nosetests

branches:
  only:
    - master
    - develop
